import "../css/style.css";
import CommonLayout from "./componets/common/CommonLayout";
import MainLayout from "./componets/common/MainLayout";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CommonLayout>
          <MainLayout>
            {children}
          </MainLayout>
        </CommonLayout>
      </body>
    </html>
  );
}