import React from 'react'
import Order from './Order';


export const metadata = {
  title: "My Dashboard",
  description: "Generated by create next app",
};


export default function page() {
  return (
    <div>
      <Order/>
    </div>
  )
}
