import React from 'react'
import Dashboard from './Dashboard'

export const metadata = {
  title: "My Dashboard",
  description: "Generated by create next app",
};


export default function page() {
  return (
    <div>
      <Dashboard/>
    </div>
  )
}
