import React from 'react'
import AboutUs from './AboutUs'
// import AboutUs from './AboutUs'

export const metadata = {
  title: "About Us",
  description: "Generated by create next app"
}

export default function page() {
  return (
    <div>
      <AboutUs/>
    </div>
  )
}
